{{- if .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unleash.fullname" . }}
  labels:
{{ include "unleash.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
{{ .content | indent 4 }}
{{- end }}
{{- end }}
