{{- $fullName := include "unleash.fullname" . -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "unleash.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "unleash.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    {{- with .Values.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- if ne .Values.gke.workloadIdentityEmail "" }}
    iam.gke.io/gcp-service-account: {{ .Values.gke.workloadIdentityEmail }}
    {{- end }}