existingSecrets:
  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: secretname
        key: secretkey

volumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

volumes:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"

postgres:
  enabled: false
