---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unleash-proxy.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "unleash-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unleash-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unleash-proxy.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unleash-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "unleash-proxy.name" . }}
          env:
            {{- if .Values.proxy.apiTokenSecret.enabled }}
            - name: UNLEASH_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.proxy.apiTokenSecret.name }}"
                  key: "{{ .Values.proxy.apiTokenSecret.key }}"
            {{ else }}
            - name: UNLEASH_API_TOKEN
              value: "{{ .Values.proxy.apiToken }}"
            {{- end }}
            {{- if .Values.proxy.clientKeysSecret.enabled }}
            - name: UNLEASH_PROXY_CLIENT_KEYS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.proxy.clientKeysSecret.name }}"
                  key: "{{ .Values.proxy.clientKeysSecret.key }}"
            {{ else }}
            - name: UNLEASH_PROXY_CLIENT_KEYS
              value: "{{ join "," .Values.proxy.clientKeys }}"
            {{- end }}
            - name: UNLEASH_URL
              {{- if .Values.edge.enable }}
              value: "http://localhost:3063/api"
              {{- else }}
              value: "{{ .Values.proxy.serverHost }}"
              {{- end }}
           {{- if .Values.proxy.logLevel }}
            - name: LOG_LEVEL
              value: "{{ .Values.proxy.logLevel }}"
           {{- end }}
           {{- if .Values.proxy.unleashAppName }}
            - name: UNLEASH_APP_NAME
              value: "{{ .Values.proxy.unleashAppName }}"
           {{- end }}
           {{- if .Values.proxy.environment }}
            - name: UNLEASH_ENVIRONMENT
              value: "{{ .Values.proxy.environment }}"
           {{- end }}
           {{- if .Values.proxy.unleash_instance_id }}
            - name: UNLEASH_INSTANCE_ID
              value: "{{ .Values.proxy.unleash_instance_id }}"
           {{- end }}
           {{- if .Values.existingSecrets }}
             {{- toYaml .Values.existingSecrets | nindent 12 }}
           {{- end }}
           {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
           {{- end }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.mountSecretName }}
          volumeMounts:
          - mountPath: /mnt/secrets
            name: mount-secrets
            readOnly: true
           {{ if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
           {{- end }}
          {{- else }}
          {{ if .Values.volumeMounts }}
          volumeMounts:
              {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.edge.enable }}
        - name: unleash-edge
          args:
            - "offline"
          env:
            - name: TOKENS
              value: {{ .Values.proxy.apiToken }}
            - name: BOOTSTRAP_FILE
              value: /data/config/features.json
              image: "unleashorg/unleash-edge:v{{ .Values.edge.version }}"
            - name: PORT
              value: "{{ .Values.edge.port }}"
            - name: WORKERS
              value: "1"
            - name: INTERFACE
              value: "::"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.edge.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /internal-backstage/health
              port: http
          readinessProbe:
            httpGet:
              port: http
              path: /internal-backstage/ready
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 20m
              memory: 32Mi
          volumeMounts:
            - mountPath: "/data/config"
              name: edge-features
        {{- end }}
      {{- if or .Values.edge.enable .Values.mountSecretName .Values.volumes }}
      volumes:
        {{- if .Values.mountSecretName }}
        - name: mount-secrets
          secret:
            secretName: {{ .Values.mountSecretName }}
        {{- end }}
        {{- if .Values.edge.enable }}
        - name: edge-features
          configMap:
            name: edge-features
        {{- end }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
      - {{ toYaml . | nindent 8 | trim }}
        labelSelector:
          matchLabels:
            {{- include "unleash-proxy.selectorLabels" $ | nindent 12 }}
        matchLabelKeys:
          - pod-template-hash
      {{- end }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
