apiVersion: v1
kind: Service
metadata:
  name: {{ include "unleash-proxy.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    {{- include "unleash-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unleash-proxy.selectorLabels" . | nindent 4 }}
